Add example script for writing all Myo data to file.
qtux/myo-raw pull request #5
Opened 2018-05-16 19:57 UTC by jamieforth

2018-05-20 14:20 UTC, qtux requested changes
Thank you for your nice example! I added some comments with minor issues. Could you please fix them?

2018-05-20 14:20 UTC, qtux commented on examples/myo-record.py
> +import argparse
Could you please add a MIT license header with your credentials to the top of the file (see other files for an example)?

2018-05-20 14:20 UTC, qtux commented on examples/myo-record.py
> +
The Myo class seems unnecessary to me. Is it here to give an example on how to implement a custom Myo class deriving from MyoRaw? I think it is better to remove the class and keep the example concise.

2018-05-20 14:20 UTC, qtux commented on examples/myo-record.py
> +
Could you please use os.path.join to create the path, e.g. os.path.join(outdir, now + '_emg.csv')

2018-05-20 14:20 UTC, qtux commented on examples/myo-record.py
> +    m = Myo(args.tty)
As mentioned above: I prefer MyoRaw here instead of using the custom Myo class.

2018-06-05 19:37 UTC, jamieforth commented on examples/myo-record.py
> +import argparse
Added.

2018-06-05 19:38 UTC, jamieforth commented on examples/myo-record.py
> +
As outdir was already a Path I used Path.joinpath, hope that's OK.

2018-06-05 19:39 UTC, jamieforth commented on examples/myo-record.py
> +
Yes there's no need for the custom class here!

2018-06-05 19:41 UTC, qtux commented on examples/myo-record.py
> +
Looks good to me.

2018-06-05 19:48 UTC, qtux approved these changes

2018-06-05 19:48 UTC, merged

2018-06-05 19:49 UTC, qtux commented
Thank you very much for your nice example! It is working fine :-).